#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.subdir"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.admin_pw = "acab"
    args.init_main_permission = "all_users"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    #test_upgrade_from.8236072.name = "Upgrade from 1.14.5~ynh1 (v1)"
    test_upgrade_from.ada997b121bbcdf2b70467f4e5484cd19d4ca65f.name = "Upgrade from 2.14.7~ynh1"
