#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove "$app"
	yunohost service remove "$app-consumer"
	yunohost service remove "$app-scheduler"
	yunohost service remove "$app-task-queue"
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd

ynh_config_remove_systemd "$app-consumer"
ynh_config_remove_systemd "$app-scheduler"
ynh_config_remove_systemd "$app-task-queue"

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

# Remove the dedicated NGINX config
ynh_config_remove_nginx

# Remove metapackage and its dependencies
ynh_redis_remove_db "$redis_db"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
