#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	ynh_script_progression --message="Removing $app service integration..." --weight=1
	yunohost service remove "$app"
	yunohost service remove "$app-consumer"
	yunohost service remove "$app-scheduler"
	yunohost service remove "$app-task-queue"
fi

# Remove the dedicated systemd config
ynh_remove_systemd_config --service="$app"
ynh_remove_systemd_config --service="$app-consumer"
ynh_remove_systemd_config --service="$app-scheduler"
ynh_remove_systemd_config --service="$app-task-queue"

# Remove the app-specific logrotate config
ynh_remove_logrotate

# Remove the dedicated NGINX config
ynh_remove_nginx_config

# Remove metapackage and its dependencies
ynh_redis_remove_db "$redis_db"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
